services:
  postgres:
    container_name: ride_db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5433:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
